Repository fregante/GhostText, pull requests merged in 2021-02, with the labels that each got.

#176 Focus browser after disconnection
  browser/scripts/background.js
  browser/scripts/content.js
Labels: enhancement

#186 Automatically pick the field more often
  browser/scripts/content.js
Labels: enhancement

#193 Add information and improve styling of options page
  package-lock.json
  package.json
  readme.md
  source/background.js
  source/ghost-text.js
  source/humane-ghosttext.css
  source/options.html
Labels: browser, documentation

#194 Meta: Add building/contributing documentation
  contributing.md
  package.json
  source/README.md
Labels: browser, documentation

#188 Add Safari version
  package.json
  promo/demo-screen-safari.png
  promo/demo-screen.png
  promo/demo-screen.sketch
  promo/graphics.sketch
  readme.md
  safari/.gitignore
  safari/AppIcon.sketch
  safari/GhostText Extension/GhostText_Extension.entitlements
  safari/GhostText Extension/Info.plist
  safari/GhostText Extension/SafariWebExtensionHandler.swift
  safari/GhostText.xcodeproj/project.pbxproj
  safari/GhostText/AppDelegate.swift
  safari/GhostText/Assets.xcassets/AccentColor.colorset/Contents.json
  safari/GhostText/Assets.xcassets/AppIcon.appiconset/Contents.json
  safari/GhostText/Assets.xcassets/AppIcon.appiconset/icon1024.png
  safari/GhostText/Assets.xcassets/AppIcon.appiconset/icon128.png
  safari/GhostText/Assets.xcassets/AppIcon.appiconset/icon16.png
  safari/GhostText/Assets.xcassets/AppIcon.appiconset/icon256.png
  safari/GhostText/Assets.xcassets/AppIcon.appiconset/icon32.png
  safari/GhostText/Assets.xcassets/AppIcon.appiconset/icon512.png
  safari/GhostText/Assets.xcassets/AppIcon.appiconset/icon64.png
  safari/GhostText/Assets.xcassets/Contents.json
  safari/GhostText/Base.lproj/Main.storyboard
  safari/GhostText/GhostText.entitlements
  safari/GhostText/Info.plist
  safari/GhostText/ViewController.swift
  safari/Shared.xcconfig
  safari/app-store-description.txt
  safari/app-store-keywords.txt
  source/background.js
  source/icons/icon128.png
  source/icons/icon16.png
  source/icons/icon256.png
  source/icons/icon32.png
  source/icons/icon48.png
  source/icons/icon64.png
  source/images/icon_128.png
  source/images/icon_19.png
  source/images/icon_48.png
  source/manifest.json
Labels: safari

#197 Slightly improve notifications style
  source/humane-ghosttext.css
Labels: browser

#198 Reduce vim plugin choice in readme discarding outdated ones
  readme.md
Labels: documentation

#195 Bubble synthetic event so more websites can catch them
  source/ghost-text.js
Labels: browser, enhancement

#199 Meta: Move readme content to mini site
  readme.md
Labels: documentation

#203 Support fields nested in CodeMirror widgets
  source/ghost-text.js
Labels: enhancement
