Repository fregante/GhostText, pull requests merged in 2023-03, with the labels that each got.

#245 Add notification and focus options
  .gitignore
  source/background.js
  source/ghost-text.js
  source/options-storage.js
  source/options.css
  source/options.html
Labels: enhancement

#239 Add support for Monaco Editor
  source/ghost-text.js
  source/unsafe-messenger.js
Labels: enhancement

#253 Add support for CodeMirror 6
  package-lock.json
  package.json
  source/ghost-text.js
  source/unsafe-messenger.js
Labels: enhancement, new site support

#269 Add shortcut to disconnect fields
  source/background.js
  source/manifest.json
Labels: enhancement

#270 Fix status badge on Safari
  safari/prepare-release.sh
  source/background.js
Labels: bug, safari

#277 Restore keyboard shortcuts in Firefox
  source/background.js
Labels: bug, firefox

#280 Handle "Load failed" message on Safari
  source/background.js
Labels: UX, safari
